name: aws cli environment (docker image)

on:
  push:
    branches:
      - chore/github-action
env:
  AWS_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  aws-cli:
    name: Setup AWS CLI environment
    runs-on: ubuntu-latest
    container: amazon/aws-cli:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test AWS CLI commands
        run: |
          aws s3 ls
