name: build-and-test

on:
  push:
    branches: [ chore/github-action ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bash commands
        run: |
          ls -alh
