name: conventional-commit (custom action)

on:
  push:
    branches:
      - chore/github-action

jobs:
  conventional-commit:
    name: Check conventional commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conventional commits
        uses: no-brand/conventional-commits-action@v1.2
